{% set name = "geospatial-ml" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/geospatial-ml-{{ version }}.tar.gz
  sha256: 68e58ecf3a5b56361da9264d870286a4f729dfbaf77b45da15e1c76a946134da

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 3

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - geospatial
    - keras
    - pytorch
    - pytorch-lightning
    - scikit-gstat
    - scikit-learn
    - scikit-plot
    - tensorflow
    - torchgeo
    - uvicorn
    - verde
    # - vaex  # [not py==310]

test:
  imports:
    - geospatial_ml
  # commands:
  #   - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/giswqs/geospatial-ml
  summary: A Python package for installing commonly used packages for geospatial analysis and machine learning with only one command.  
  description: A Python package for installing commonly used packages for geospatial analysis and machine learning with only one command. 
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://ml.gishub.org
  dev_url: https://github.com/giswqs/geospatial-ml
extra:
  recipe-maintainers:
    - giswqs
