{% set name = "geospatial-ml" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geospatial-ml-{{ version }}.tar.gz
  sha256: 8a6c6a62731d69df7983cd52d290f9952b7ec76f3570cea892a28b1347f888d2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - geospatial
    - keras
    - pytorch
    - pytorch-lightning
    - scikit-gstat
    - scikit-learn
    - scikit-plot
    - tensorflow
    - torchgeo
    - verde

test:
  imports:
    - geospatial_ml
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/giswqs/geospatial-ml
  summary: A collection of Python packages for geospatial analysis and machine learning.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
